### ISSUE TITLE
something's funky in testOrderBy

### ISSUE THREAD

**Issue by presentoccupant** [hawkfish/olapscript#59] opened 2022-08-27 02:53 UTC
Running testOrderBy in olapscript-tests-and-utils.  The result is correct, but row 1 is blank on the output sheet.

**Comment by hawkfish** [comment] 2022-08-28 00:04
Might be related to the new `fromSheet` options.

**Comment by hawkfish** [comment] 2022-08-28 02:06
This is probably a duplicate of #60 .

**Comment by presentoccupant** [comment] 2022-08-28 02:37
Tested and behaves as expected.

**Closed** 2022-08-28 02:37 UTC
Labels: bug
